apiVersion: v1
kind: Namespace
metadata:
  name: cilsy-staging

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cilsy-staging
  name: pesbuk-configmap-secret-staging
data:
  config.php: |
    <?php
    $db_host = getenv("DB_HOST");
    $db_user = getenv("DB_USER");
    $db_pass = getenv("DB_PASS");
    $db_name = getenv("DB_NAME");
    try {    
      //create PDO connection
      $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
    } catch(PDOException $e) {
      //show error
      die("Terjadi masalah: " . $e->getMessage());
    }
    ?>
    
---

apiVersion: v1
kind: Secret
metadata:
  namespace: cilsy-staging
  name: pesbuk-secret-staging
type: Opaque
data:
  DB_HOST: Y2lsc3liaWdwcm9kYi5jdng1aXdzc291dWYuYXAtc291dGhlYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  DB_USER: ZGV2b3BzY2lsc3k=
  DB_PASS: MTIzNDU2Nzg5MA==
  DB_NAME: cGVzYnVrc3RhZ2luZ2Ri
  MYSQL_ROOT_PASSWORD: YmlncHJvY2lsc3k=
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cilsy-staging
  name: pesbuk-staging
  labels:
    app: pesbuk-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pesbuk-staging
  template:
    metadata:
      labels:
        app: pesbuk-staging
    spec:
      volumes:
        - name: config-secret
          configMap:
            name: pesbuk-configmap-secret-staging
      containers:
      - name: pesbuk-staging
        image: hansenfernando/cilsypesbuk-staging:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-secret
          mountPath: "/var/www/html/config.php"
          subPath: "config.php"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: pesbuk-secret-staging
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pesbuk-secret-staging
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: pesbuk-secret-staging
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pesbuk-secret-staging
              key: DB_NAME

---

kind: Service
apiVersion: v1
metadata:
  namespace: cilsy-staging
  name: pesbuk-svc-staging
spec:
  selector:
    app: pesbuk-staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: cilsy-staging
  name: pesbuk-ingress-staging
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.ingress.kubernetes.io/affinity: "cookie"
     nginx.ingress.kubernetes.io/session-cookie-name: "pesbuk-staging-cookie"
     nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
     nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/affinity-mode: persistent
     nginx.ingress.kubernetes.io/session-cookie-hash: sha1
spec:
  rules:
  - host: stagingpesbuk.hansenfernando.xyz      
    http:
      paths:
        - backend:
           serviceName: pesbuk-svc-staging
           servicePort: 80
